version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vedant-backend
    container_name: vedant_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vedant_network
      - pgsql_default
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vedant-frontend
    container_name: vedant_frontend
    restart: unless-stopped
    volumes:
      - frontend_dist:/frontend
    networks:
      - vedant_network

  redis:
    image: redis:alpine
    container_name: vedant_redis
    restart: unless-stopped
    networks:
      - vedant_network

networks:
  vedant_network:
    driver: bridge

  pgsql_default:
    external: true

volumes:
  frontend_dist:
