services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vedant-backend
    container_name: vedant_backend
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "127.0.0.1:9000:9000"   
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vedant_network
      - pgsql_default
    depends_on:
      - redis

  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vedant-backend
    container_name: vedant_queue
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    command: php artisan queue:work --tries=3 --timeout=90
    depends_on:
      - redis
      - backend
    networks:
      - vedant_network
      - pgsql_default

  redis:
    image: redis:alpine
    container_name: vedant_redis
    restart: unless-stopped
    networks:
      - vedant_network

networks:
  vedant_network:
    driver: bridge

  pgsql_default:
    external: true
